version: '3.9'

services:

  postgres:
    image: postgres:15.6
    restart: always
    container_name: ${PROJECT_NAME}_postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_USER_PASSWORD}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - db-data:/var/lib/postgresql/data/
    networks:
      - local_network

  redis:
    image: redis:7.4
    restart: always
    container_name: ${PROJECT_NAME}_redis
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - cache:/data
    networks:
      - local_network

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: ${PROJECT_NAME}_rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_USER_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - local_network

  django_gateway:
    container_name: ${PROJECT_NAME}_gateway
    build:
      context: ./django_gateway/
    restart: always
    command:
      - /bin/sh
      - -c
      - |
        python api_gateway/manage.py makemigrations
        python api_gateway/manage.py makemigrations api_gateway
        python api_gateway/manage.py migrate
        echo "WEB: Migrations process done ..."
        python api_gateway/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - rabbitmq
      - redis
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_USER_PASSWORD=${DB_USER_PASSWORD}
      - DB_HOST=${PROJECT_NAME}_postgres
      - DB_PORT=5432
      - SECRET_KEY=${SECRET_KEY}
      - AUTH_TOKEN_KEY=${AUTH_TOKEN_KEY}
      - WS_TOKEN_KEY=${WS_TOKEN_KEY}
      - RABBITMQ_HOST=${PROJECT_NAME}_rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_USER_PASSWORD=${RABBITMQ_USER_PASSWORD}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=${PROJECT_NAME}_redis
      - REDIS_PORT=6379

    networks:
      - local_network

networks:
  local_network:


volumes:
  db-data:
  cache:
    driver: local
